# Generated by Django 4.2.7 on 2023-12-03 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
